entityDependencies:
  Customer: []
  Invoice: [SalesOrder]
  NestedProfile: []
  PurchaseOrder: [Supplier]
  SalesOrder: [Customer]
  SalesOrderCreated: []
  Selfie: []
  Supplier: []
  User: []
  UserLog: [User]
  UserSetting: [User]
  Event: []
  _User: [User]

entityNamespaces:
  Customer: tailordb
  Invoice: tailordb
  NestedProfile: tailordb
  PurchaseOrder: tailordb
  SalesOrder: tailordb
  SalesOrderCreated: tailordb
  Selfie: tailordb
  Supplier: tailordb
  User: tailordb
  UserLog: tailordb
  UserSetting: tailordb
  Event: analyticsdb
