entityDependencies:
  Customer: []
  Invoice: [SalesOrder]
  NestedProfile: []
  PurchaseOrder: [Supplier]
  SalesOrder: [Customer]
  SalesOrderCreated: []
  Selfie: []
  Supplier: []
  User: []
  UserLog: [User]
  UserSetting: [User]
  Event: []
  _User: [User]
