entityDependencies:
  Customer: []
  Invoice: [SalesOrder]
  NestedProfile: []
  PurchaseOrder: [Supplier]
  SalesOrder: [Customer]
  SalesOrderCreated: []
  Selfie: []
  Supplier: []
  User: []
  UserSetting: [User]
